# yazi

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM


# -- tmux
# TODO https://timvw.be/2026/02/12/tmux-training-wheels-a-zellij-inspired-shortcut-hints-bar/
set -g mouse on
set -g base-index 1
# for nvim org mode
set -s extended-keys always
set -s extended-keys-format csi-u          # tmux 3.5+ เท่านั้น ถ้าเก่ากว่าให้ลบบรรทัดนี้
set -as terminal-features 'xterm-kitty:extkeys'

set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_command}'
set -g set-titles on
set -g set-titles-string '#{pane_current_path}'
set-option -g status-style bg="#000000"

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g @tmux_power_theme 'violet'
# set -g @tmux_power_right_arrow_icon    ''
set -g @tmux_power_right_arrow_icon    ' '
# set -g @tmux_power_left_arrow_icon     ''
set -g @tmux_power_left_arrow_icon     ' '
set -g @tmux_power_left_a '#h'
set -g @tmux_power_show_upload_speed   false
set -g @tmux_power_show_download_speed true
set -g @tmux_power_right_y ''
set -g @tmux_power_right_z ''
set -g @tmux_power_right_w '#(~/.local/bin/tmux-memory)'
# use alt hjkl to move between pane.

# Set python with pynvim installed.
# Use an absolute path because if you activate a python virtual environment, the pynvim may not be installed on that environment.
# set -g @treemux-python-command '/usr/bin/python3'  # default is '/usr/bin/python3'

# If you want to completely isolate the treemux's nvim config and data from your main nvim config and data, set NVIM_APPNAME.
# This will make treemux use '~/.config/nvim-treemux', '~/.local/share/nvim-treemux'
# set -g @treemux-nvim-command 'NVIM_APPNAME=nvim-treemux nvim'  # default is 'nvim'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'wfxr/tmux-power'
# set -g @plugin 'wfxr/tmux-net-speed'
set -g @plugin 'thewtex/tmux-mem-cpu-load'


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Switch Brave tab when changing tmux windows
set-hook -g after-select-window "run-shell -b '~/.local/bin/brave-tab'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
